### ISSUE TITLE
link X #

### ISSUE THREAD

**Issue by keren-cw** [keren-cw/test#30]
[Checklist Web](https://docs.google.com/spreadsheets/d/1UniZpn-JFZYELdnorSyHspnAFYXM8uxgSpCEO9T1y-E/edit#gid=1386834576)
[Checklist Mobile](https://docs.google.com/spreadsheets/d/1mJka5muMFOBF8E3sKBLqCfISbPoINY19kn2l38VllUg/edit#gid=1386834576)
- [ ] Web: [#14 ](https://github.com/cloudwalk/projects/issues/14) It's no working yet. The merchant approved with POS buy another one.
- [ ] Web and App: In the fees page, we have to replace (.) for (,). [Image evidence](https://drive.google.com/file/d/17fswxQl3eL-HmGHJh-HpUK2pVNOMGpVG/view?usp=sharing)
- [ ] Image share of Payment link is in old banner (the red one) [Image evidence](https://drive.google.com/file/d/1JJqG-_Fhd8E73G28nwExgtgEuFX53hhX/view?usp=sharing)
- [ ] App: Fees about 8, 9, 10 and 11x is with higher value than in the real fees table here > Table new fees
- [ ] App: [ The date time is not with 30 days + SLA total ]( https://github.com/cloudwalk/infinitepay-dashboard-flutter/issues/244)
- [ ] Web: [Up date the competition fees about Payment link](https://github.com/cloudwalk/infinitepay-landing/issues/521)
- [ ] Web: [[Dados bancários] The bank field has a bug](https://github.com/cloudwalk/infinitepay-landing/issues/519)
- [ ] Web: [[Pagina de indicaçao] Bug when we try to access the Simulador page](https://github.com/cloudwalk/infinitepay-landing/issues/520)
